import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

const LANGS: Record<string, Record<string, string>> = {
  uz: {
    'nav.overview': "Umumiy ko'rinish",
    'nav.properties': 'Mulklarim',
    'nav.requests': "So'rovlar",
    'nav.payments': "To'lovlar",
    'nav.settings': 'Sozlamalar',
    'nav.logout': 'Chiqish',

    'overview.title': 'Xush kelibsiz! 👋',
    'overview.subtitle': 'Bugungi holat va yangiliklar',
    'overview.stat_listings': "Aktiv e'lonlar",
    'overview.stat_requests': "Yangi so'rovlar",
    'overview.stat_income': 'Oylik daromad',
    'overview.stat_views': "Ko'rishlar",
    'overview.recent': "So'nggi so'rovlar",
    'overview.see_all': "Barchasini ko'rish →",
    'overview.add_property': "+ Mulk qo'shish",
    'overview.no_requests': "So'rovlar mavjud emas",
    'overview.col_property': 'Mulk',
    'overview.col_checkin': 'Kirish',
    'overview.col_checkout': 'Chiqish',
    'overview.col_nights': 'Tunlar',
    'overview.col_amount': 'Summa',
    'overview.col_status': 'Holat',

    'requests.title': "So'rovlar",
    'requests.col_property': 'Mulk',
    'requests.col_type': 'Tur',
    'requests.col_checkin': 'Kirish',
    'requests.col_checkout': 'Chiqish',
    'requests.col_nights': 'Tunlar',
    'requests.col_amount': 'Summa',
    'requests.col_status': 'Holat',
    'requests.col_actions': 'Amallar',
    'requests.approve': '✔ Tasdiqlash',
    'requests.reject': '✘ Rad etish',
    'requests.empty': "So'rovlar mavjud emas",
    'requests.reject_prompt': 'Rad etish sababi (ixtiyoriy):',

    'payments.title': "To'lovlar",
    'payments.col_date': 'Sana',
    'payments.col_amount': 'Summa',
    'payments.col_status': 'Holat',
    'payments.col_method': "To'lov usuli",
    'payments.empty': "To'lovlar mavjud emas",

    'properties.title': 'Mulklarim',
    'properties.add_btn': '+ Yangi mulk',
    'properties.form_edit': 'Mulkni tahrirlash',
    'properties.form_add': "Yangi mulk qo'shish",
    'properties.empty':
      'Hali mulk qo\'shilmagan. "+Yangi mulk" tugmasini bosing.',
    'properties.edit': '✏️ Tahrirlash',
    'properties.delete': "🗑️ O'chirish",
    'properties.delete_confirm': "Haqiqatan ham o'chirmoqchimisiz?",
    'properties.saving': 'Saqlanmoqda...',
    'properties.save': 'Saqlash',
    'properties.add_submit': "Qo'shish",
    'properties.cancel': 'Bekor qilish',
    'properties.added': "Mulk qo'shildi!",
    'properties.updated': 'Mulk yangilandi!',
    'properties.deleted': "Mulk o'chirildi",

    'settings.title': 'Sozlamalar',
    'settings.personal_info': "Shaxsiy ma'lumotlar",
    'settings.first_name': 'Ism',
    'settings.last_name': 'Familiya',
    'settings.phone': 'Telefon',
    'settings.language': 'Interfeys tili',
    'settings.save': 'Saqlash',
    'settings.saving': 'Saqlanmoqda...',
    'settings.saved': "Ma'lumotlar saqlandi!",
    'settings.close': 'Yopish',
    'settings.danger_zone': 'Xavfli zona',
    'settings.danger_desc':
      'Hisobdan chiqish barcha qurilmalarda amalga oshiriladi',
    'settings.logout_btn': '🚪 Hisobdan chiqish',
  },
  ru: {
    'nav.overview': 'Обзор',
    'nav.properties': 'Мои объекты',
    'nav.requests': 'Запросы',
    'nav.payments': 'Платежи',
    'nav.settings': 'Настройки',
    'nav.logout': 'Выйти',

    'overview.title': 'Добро пожаловать! 👋',
    'overview.subtitle': 'Сегодняшний статус и новости',
    'overview.stat_listings': 'Активные объявления',
    'overview.stat_requests': 'Новые запросы',
    'overview.stat_income': 'Месячный доход',
    'overview.stat_views': 'Просмотры',
    'overview.recent': 'Последние запросы',
    'overview.see_all': 'Посмотреть все →',
    'overview.add_property': '+ Добавить объект',
    'overview.no_requests': 'Запросов нет',
    'overview.col_property': 'Объект',
    'overview.col_checkin': 'Заезд',
    'overview.col_checkout': 'Выезд',
    'overview.col_nights': 'Ночи',
    'overview.col_amount': 'Сумма',
    'overview.col_status': 'Статус',

    'requests.title': 'Запросы',
    'requests.col_property': 'Объект',
    'requests.col_type': 'Тип',
    'requests.col_checkin': 'Заезд',
    'requests.col_checkout': 'Выезд',
    'requests.col_nights': 'Ночи',
    'requests.col_amount': 'Сумма',
    'requests.col_status': 'Статус',
    'requests.col_actions': 'Действия',
    'requests.approve': '✔ Подтвердить',
    'requests.reject': '✘ Отклонить',
    'requests.empty': 'Запросов нет',
    'requests.reject_prompt': 'Причина отклонения (необязательно):',

    'payments.title': 'Платежи',
    'payments.col_date': 'Дата',
    'payments.col_amount': 'Сумма',
    'payments.col_status': 'Статус',
    'payments.col_method': 'Способ оплаты',
    'payments.empty': 'Платежей нет',

    'properties.title': 'Мои объекты',
    'properties.add_btn': '+ Новый объект',
    'properties.form_edit': 'Редактировать объект',
    'properties.form_add': 'Добавить новый объект',
    'properties.empty': 'Объекты еще не добавлены. Нажмите "+Новый объект".',
    'properties.edit': '✏️ Редактировать',
    'properties.delete': '🗑️ Удалить',
    'properties.delete_confirm': 'Вы действительно хотите удалить?',
    'properties.saving': 'Сохранение...',
    'properties.save': 'Сохранить',
    'properties.add_submit': 'Добавить',
    'properties.cancel': 'Отмена',
    'properties.added': 'Объект добавлен!',
    'properties.updated': 'Объект обновлён!',
    'properties.deleted': 'Объект удалён',

    'settings.title': 'Настройки',
    'settings.personal_info': 'Личные данные',
    'settings.first_name': 'Имя',
    'settings.last_name': 'Фамилия',
    'settings.phone': 'Телефон',
    'settings.language': 'Язык интерфейса',
    'settings.save': 'Сохранить',
    'settings.saving': 'Сохранение...',
    'settings.saved': 'Данные сохранены!',
    'settings.close': 'Закрыть',
    'settings.danger_zone': 'Опасная зона',
    'settings.danger_desc': 'Выход из системы на всех устройствах',
    'settings.logout_btn': '🚪 Выйти из аккаунта',
  },
  en: {
    'nav.overview': 'Overview',
    'nav.properties': 'My Properties',
    'nav.requests': 'Requests',
    'nav.payments': 'Payments',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',

    'overview.title': 'Welcome! 👋',
    'overview.subtitle': "Today's status and updates",
    'overview.stat_listings': 'Active Listings',
    'overview.stat_requests': 'New Requests',
    'overview.stat_income': 'Monthly Income',
    'overview.stat_views': 'Views',
    'overview.recent': 'Recent Requests',
    'overview.see_all': 'See all →',
    'overview.add_property': '+ Add Property',
    'overview.no_requests': 'No requests found',
    'overview.col_property': 'Property',
    'overview.col_checkin': 'Check-in',
    'overview.col_checkout': 'Check-out',
    'overview.col_nights': 'Nights',
    'overview.col_amount': 'Amount',
    'overview.col_status': 'Status',

    'requests.title': 'Requests',
    'requests.col_property': 'Property',
    'requests.col_type': 'Type',
    'requests.col_checkin': 'Check-in',
    'requests.col_checkout': 'Check-out',
    'requests.col_nights': 'Nights',
    'requests.col_amount': 'Amount',
    'requests.col_status': 'Status',
    'requests.col_actions': 'Actions',
    'requests.approve': '✔ Approve',
    'requests.reject': '✘ Reject',
    'requests.empty': 'No requests found',
    'requests.reject_prompt': 'Rejection reason (optional):',

    'payments.title': 'Payments',
    'payments.col_date': 'Date',
    'payments.col_amount': 'Amount',
    'payments.col_status': 'Status',
    'payments.col_method': 'Payment Method',
    'payments.empty': 'No payments found',

    'properties.title': 'My Properties',
    'properties.add_btn': '+ New Property',
    'properties.form_edit': 'Edit Property',
    'properties.form_add': 'Add New Property',
    'properties.empty': 'No properties added yet. Click "+New Property".',
    'properties.edit': '✏️ Edit',
    'properties.delete': '🗑️ Delete',
    'properties.delete_confirm': 'Are you sure you want to delete this?',
    'properties.saving': 'Saving...',
    'properties.save': 'Save',
    'properties.add_submit': 'Add',
    'properties.cancel': 'Cancel',
    'properties.added': 'Property added!',
    'properties.updated': 'Property updated!',
    'properties.deleted': 'Property deleted',

    'settings.title': 'Settings',
    'settings.personal_info': 'Personal Information',
    'settings.first_name': 'First Name',
    'settings.last_name': 'Last Name',
    'settings.phone': 'Phone',
    'settings.language': 'Interface Language',
    'settings.save': 'Save',
    'settings.saving': 'Saving...',
    'settings.saved': 'Data saved successfully!',
    'settings.close': 'Close',
    'settings.danger_zone': 'Danger Zone',
    'settings.danger_desc': 'Logout will be performed on all devices',
    'settings.logout_btn': '🚪 Logout',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private langSubject = new BehaviorSubject<string>(
    typeof localStorage !== 'undefined'
      ? localStorage.getItem('mulkchi_lang') || 'uz'
      : 'uz',
  );
  currentLang$ = this.langSubject.asObservable();

  setLanguage(lang: string): void {
    localStorage.setItem('mulkchi_lang', lang);
    this.langSubject.next(lang);
  }

  getCurrentLang(): string {
    return this.langSubject.getValue();
  }

  t(key: string): string {
    const lang = this.getCurrentLang();
    return LANGS[lang]?.[key] ?? LANGS['uz']?.[key] ?? key;
  }
}
